### ISSUE TITLE
ocaml-bundle_x86.tar.gz

### ISSUE THREAD

**Issue by abigcoder04** [QuantumPackage/qp2-dependencies#1]
Can I download ocaml-bundle_x86.tar.gz package from the official website of qp now?

**Comment by abigcoder04** [comment]
Because I used this compressed package to install OCAML before, I hope you can download this installation package through your blog. I would be very honored if I could get your help!

**Comment by scemama** [comment]
> Can I download ocaml-bundle_x86.tar.gz package from the official website of qp now?

No, you will never be able to download officially the external dependencies of QP from the QP repository. 
When you install QP, we assume that you were successful in the installation of the dependencies, and this is where the support starts. If we provide an official way to install the dependencies, the users will ask us to provide support on the dependencies, which is not our role.
So the current repository exists to help the users, but no support is provided. 

> Because I used this compressed package to install OCAML before, I hope you can download this installation package through your blog. I would be very honored if I could get your help!

If you clone this repository, you can find a commit in the past where `ocaml-bundle_x86.tar.gz` was present. You can get it there.

It was recently replaced by `x86_64/opampack.tar.gz` because it also offers a possibility of installation of OCaml for ARM CPUs under `aarch/opampack.tar.gz`, and it is compatible with any version of the OCaml compiler.
